"""Canonical vehicle make/model catalog (Israel market).

Source of truth for the frontend's cascading manufacturer -> model dropdowns.
Not exhaustive, but covers the brands/models common on Israeli roads.
"""

VEHICLE_CATALOG: dict[str, list[str]] = {
    "Toyota": ["Corolla", "Yaris", "Camry", "RAV4", "C-HR", "Auris", "Prius",
               "Land Cruiser", "Highlander", "Hilux", "Aygo"],
    "Hyundai": ["i10", "i20", "i25", "Accent", "i30", "Elantra", "Ioniq",
                "Ioniq 5", "Tucson", "ix35", "Kona", "Santa Fe", "Bayon"],
    "Kia": ["Picanto", "Rio", "Ceed", "Stonic", "Sportage", "Niro", "Seltos",
            "Sorento", "EV6", "Sphera", "XCeed"],
    "Mazda": ["2", "3", "6", "CX-3", "CX-30", "CX-5", "CX-60", "MX-5"],
    "Skoda": ["Fabia", "Scala", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq",
              "Enyaq"],
    "Volkswagen": ["Polo", "Golf", "Passat", "Arteon", "T-Cross", "T-Roc",
                   "Tiguan", "Touran", "ID.3", "ID.4"],
    "Suzuki": ["Swift", "Baleno", "Ignis", "Vitara", "S-Cross", "Jimny",
               "Crossover"],
    "Nissan": ["Micra", "Juke", "Qashqai", "X-Trail", "Leaf", "Ariya"],
    "Honda": ["Jazz", "Civic", "HR-V", "CR-V"],
    "Mitsubishi": ["Space Star", "Attrage", "ASX", "Eclipse Cross", "Outlander"],
    "Renault": ["Clio", "Megane", "Captur", "Kadjar", "Koleos", "Zoe", "Austral"],
    "Peugeot": ["208", "308", "2008", "3008", "5008", "e-208"],
    "Citroen": ["C3", "C4", "C5 Aircross", "C3 Aircross"],
    "Seat": ["Ibiza", "Leon", "Arona", "Ateca"],
    "Cupra": ["Formentor", "Born", "Leon", "Ateca"],
    "BMW": ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series",
            "X1", "X3", "X5", "i3", "i4", "iX"],
    "Mercedes-Benz": ["A-Class", "B-Class", "C-Class", "E-Class", "CLA",
                      "GLA", "GLC", "GLE", "EQA", "EQC"],
    "Audi": ["A1", "A3", "A4", "A5", "A6", "Q2", "Q3", "Q5", "Q8", "e-tron"],
    "Ford": ["Fiesta", "Focus", "Puma", "Kuga", "Mustang Mach-E"],
    "Opel": ["Corsa", "Astra", "Crossland", "Mokka", "Grandland"],
    "Chevrolet": ["Spark", "Aveo", "Cruze", "Traverse"],
    "Tesla": ["Model 3", "Model Y", "Model S", "Model X"],
    "MG": ["3", "4", "5", "ZS", "HS", "Marvel R"],
    "BYD": ["Atto 3", "Dolphin", "Seal", "Han", "Tang"],
    "Chery": ["Tiggo 4", "Tiggo 7", "Tiggo 8", "Omoda 5"],
    "Geely": ["Coolray", "Geometry C", "Emgrand"],
    "Dacia": ["Sandero", "Logan", "Duster", "Spring", "Jogger"],
    "Volvo": ["XC40", "XC60", "XC90", "S60", "C40"],
    "Subaru": ["Impreza", "XV", "Forester", "Outback"],
    "Lexus": ["CT", "UX", "NX", "RX", "IS", "ES"],
    "Jeep": ["Renegade", "Compass", "Wrangler", "Grand Cherokee"],
    "Fiat": ["500", "Panda", "Tipo", "500X"],
    "Mini": ["Cooper", "Countryman", "Clubman"],
    "SsangYong": ["Tivoli", "Korando", "Rexton", "Torres"],
    "Isuzu": ["D-Max"],
    "Alfa Romeo": ["Giulia", "Stelvio", "Tonale"],
}
